Rajan_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cms/', include('cms.urls')),
                  path('', include('blog.urls')),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', HomePage.as_view(), name='index'),
    path('blog', BlogView.as_view(), name='blogs'),
    path('blog/<str:singleblog_slug>', SinglePostView.as_view(), name='single_blog'),
    path('search', SearchView.as_view(), name='search'),
    path('gallery',GalleryView.as_view(),name='gallery'),


]

cms/urls.py
from django.urls import path
from .views import *

app_name='cms'

urlpatterns=[
    path('about/',PageView.as_view(),name='abouts'),
    path('contact/',ContactView.as_view(),name='contacts')

]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from sorl.thumbnail import ImageField
from autoslug import AutoSlugField


# from django.contrib.auth.models import User


# Create your models here.


class CategoryWiseBlog(models.Model):
    title = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from='title', unique=True)

    def __str__(self):
        return self.title


class BlogPost(models.Model):
    title = models.CharField(max_length=50)
    content = RichTextField()
    Pub_date = models.DateTimeField(auto_now=True)
    author = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from='title', unique=True)
    category = models.ForeignKey(CategoryWiseBlog, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def image(self):
        return self.bloghasimage_set.first()


class BlogHasImage(models.Model):
    blog = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    image = ImageField()


class BlogComment(models.Model):
    name = models.CharField(max_length=25)
    email = models.EmailField()
    comment = models.TextField()
    date = models.DateTimeField(auto_now=True)
    blog = models.ForeignKey(BlogPost, on_delete=models.CASCADE)


class ImageGallery(models.Model):
    title = models.CharField(max_length=50)
    image = ImageField()

    def __str__(self):
        return self.title

cms/models.py
from django.db import models
from sorl.thumbnail import ImageField
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField


class Page(models.Model):
    title = models.CharField(max_length=50)
    menu_title = models.CharField(max_length=50)
    content = RichTextField()
    image = ImageField()
    published = models.BooleanField()
    slug = AutoSlugField(populate_from='title', unique=True)

    def __str__(self):
        return self.title


class Banner(models.Model):
    title = models.CharField(max_length=50)
    image = ImageField()
    published = models.BooleanField()
    content = RichTextField()
    weight = models.IntegerField()

    def __str__(self):
        return str(self.weight)

blog/forms.py
from django.forms import ModelForm
from .models import BlogComment


class CommentForm(ModelForm):
    class Meta:
        model = BlogComment
        fields = ('name', 'email', 'comment',)

blog/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import *
from .forms import CommentForm
from cms.models import Banner
from django.core.paginator import Paginator
from cms.models import Page


# Create your views here.
class BaseView(View):
    template_context = {
        # 'blogposts': BlogPost.objects.order_by('title').all(),


    }


class HomePage(BaseView):
    def get(self, request):
        self.template_context['banners'] = Banner.objects.filter(published=True).order_by('-weight')
        return render(request, 'index.html', self.template_context)


class BlogView(BaseView):
    def get(self, request):
        self.template_context['blogs'] = BlogPost.objects.all()
        self.template_context['top_posts'] = BlogPost.objects.order_by('?')[:4]

        blog_post_list = BlogPost.objects.all()
        paginator = Paginator(blog_post_list, 2)
        page = request.GET.get('page', 1)
        self.template_context['blog_pages'] = paginator.get_page(page)
        print(paginator.page_range)
        self.template_context['paginator'] = paginator
        return render(request, 'blog.html', self.template_context)


class SinglePostView(BaseView):
    def get(self, request, singleblog_slug):
        singlepost = BlogPost.objects.get(slug=singleblog_slug)
        self.template_context['single_posts'] = singlepost
        self.template_context['top_posts'] = BlogPost.objects.order_by('-id')[:4]
        self.template_context['next_prev'] = BlogPost.objects.order_by('?')[:1]
        self.template_context['comments'] = BlogComment.objects.all()
        return render(request, 'single-blog.html', self.template_context)

    def post(self, request, singleblog_slug):
        form = CommentForm(request.POST)
        if form.is_valid():
            print("success")
            blog_review = form.save(commit=False)
            blog_review.blog = BlogPost.objects.get(slug=singleblog_slug)
            blog_review.save()

        return redirect('/blog/' + singleblog_slug)

    # print("fail")
    # return redirect('/')


class SearchView(BaseView):
    def get(self, request):
        q = request.GET.get('q', None)
        if not q:
            return redirect('/')

        self.template_context['search_results'] = BlogPost.objects.filter(title__icontains=q)
        return render(request, 'search-result.html', self.template_context)


class GalleryView(BaseView):
    def get(self, request):
        self.template_context['galleries'] = ImageGallery.objects.order_by('?')
        return render(request, 'Imagegallery.html', self.template_context)

cms/views.py
from django.shortcuts import render
from django.views import View
from blog.views import BaseView
from .models import *


# Create your views here.
class ContactView(BaseView):
    def get(self, request):
        return render(request, 'contact.html')


class PageView(BaseView):
    def get(self, request):
        self.template_context['abouts'] = Page.objects.all()
        return render(request, 'about-us.html', self.template_context)

templates/Imagegallery.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block content %}

    <section class="banner_area">
        <div class="box_1620">
            <div class="banner_inner d-flex align-items-center"
                 style="background-image: url('{% static "img/banner/gallery.jpg" %}')">

                <div class="container">
                    <div class="banner_content text-center">
                        <h2 style="color: #0b0b0b">Gallery</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Home Gallery Area =================-->
    <section class="home_gallery_area p_120">
        <div class="container">
            <div class="main_title">
                <h2>MY PHOTOGRAPHY</h2>
                <p>my best snap</p>
            </div>

        </div>
        <div class="container">
            <div class="gallery_f_inner row imageGallery1">
                {% for photo in galleries %}
                    <div class="col-lg-4 col-md-4 col-sm-6 brand manipul design print">
                        <div class="h_gallery_item">
                            <div class="g_img_item">
                                {% thumbnail photo.image "340x340" crop="center" as im %}
                                    <img src="{{ im.url }}" class="img-fluid" alt="{{ photo.title | safe }}">


                                <a class="light" href="{{ photo.image.url }}">
                                    <img src="{% static 'img/gallery/icon.png' %}" alt=""></a>
                                {% endthumbnail %}
                            </div>

                        </div>

                    </div>
                {% endfor %}
            </div>
            <div class="more_btn">
                <a class="main_btn" href="#">Load More Items</a>
            </div>
        </div>

    </section>

    <!--================End Home Gallery Area =================-->
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="img/favicon.png" type="image/png">
    <title>Rajan Khayamali</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/popup/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/flaticon/flaticon.css' %}">
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/gallerypopup.css' %}">
</head>
<body>

<!--================Header Menu Area =================-->
<header class="header_area">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container box_1620">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" href="index.html"><img src="img/logo.png" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" href="/">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'cms:abouts' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'blog:gallery' %}">Gallery</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'blog:blogs' %}">Blogs</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'cms:contacts' %}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>
<!--================Header Menu Area =================-->

{% block content %}{% endblock %}

<!--================Footer Area =================-->
<footer class="footer_area p_120">
    <div class="container">
        <div class="row footer_inner">
            <div class="col-lg-6 col-sm-6">
                <aside class="f_widget ab_widget">
                    <div class="f_title">
                        <h3>About Me</h3>
                    </div>

                    <p>Do you want to be even more successful? Learn to love learning and growth. The more effort you
                        put into improving your skills the more you get chance to get Perfect.</p>

                    <p>
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                        All rights reserved | With <i class="fa fa-heart-o"
                                                      aria-hidden="true"></i> by <a
                            href="{% url 'blog:index' %}" target="_blank">RAJAN KHAYAMALI</a>
                    </p>
                </aside>

            </div>
            <div class="col-4 col-sm-4">
            </div>
            <div class="col-2 col-sm-2">
                <aside class="f_widget social_widget">
                    <div class="f_title">
                        <h3>Follow Me</h3>
                    </div>
                    <p>Let us be social</p>
                    <ul class="list">
                        <li><a href="https://www.facebook.com/rajan.khayamali"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    </ul>
                </aside>
            </div>
        </div>
    </div>
</footer>
<!--================End Footer Area =================-->


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/stellar.js' %}"></script>
<script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
<script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'vendors/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendors/popup/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'vendors/counter-up/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'vendors/counter-up/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<!--gmaps Js-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
<script src="{% static 'js/gmaps.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>


</body>
</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% load thumbnail %}
    <section class="home_banner_area blog_banner">
        <div class="banner_inner d-flex align-items-center">
            <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0"
                 data-background=""><img style="width: 100%; height: auto;"
                                         src="{% static 'img/banner/blogbanner.jpg' %}"></div>
            <div class="container">
                <div class="blog_b_text text-center">
                    <h2>welcome to my <br/> BLOG</h2>
                </div>
            </div>
        </div>
    </section>

    <section class="blog_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="blog_left_sidebar">
                        {% for blog in blog_pages %}
                            <article class="row blog_item" style="padding-top: 30px;">
                                <div class="col-md-3">
                                    <div class="blog_info text-right">
                                        <div class="post_tag">
                                            <a class="active" href="#">{{ blog.category }}</a>

                                        </div>
                                        <ul class="blog_meta list">
                                            <li><a href="#">{{ blog.author }}<i class="lnr lnr-user"></i></a></li>
                                            <li><a href="#">{{ blog.Pub_date }}<i class="lnr lnr-calendar-full"></i></a>
                                            </li>
                                            <li><a href="#">1.2M Views<i class="lnr lnr-eye"></i></a></li>
                                            <li><a href="#">06 Comments<i class="lnr lnr-bubble"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <div class="blog_post">
                                        {% thumbnail blog.image.image "510x275" crop="center" as im %}
                                            <img src="{{ im.url }}">
                                        {% endthumbnail %}
                                        <div class="blog_details">
                                            <a href="{% url 'blog:single_blog' blog.slug %}">
                                                <h2>{{ blog.title |safe }}</h2></a>
                                            <p>{{ blog.content|truncatewords:50 | safe }}</p>
                                            <a href="{% url 'blog:single_blog' blog.slug %}"
                                               class="white_bg_btn">View More</a>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        {% endfor %}


                        <nav class="blog-pagination justify-content-center d-flex">
                            <ul class="pagination">

                                <li class="page-item">
                                    {% if blog_pages.has_previous %}
                                        <a class="page-link" href="?page={{ blog_pages.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    {% endif %}
                                </li>
                                {% for page in paginator.page_range %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a>
                                    </li>
                                {% endfor %}

                                <li class="page-item">
                                    {% if blog_pages.has_next %}
                                        <a class="page-link" href="?page={{ blog_pages.next_page_number }}"
                                           aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    {% endif %}
                                </li>

                            </ul>
                        </nav>
                    </div>
                </div>
                {% include 'partials/side-search-content.html' %}
            </div>
        </div>
    </section>
{% endblock %}
        

templates/partials/side-search-content.html
{% load thumbnail %}

<div class="col-lg-4">
    <div class="blog_right_sidebar">
        <aside class="single_sidebar_widget search_widget">
            <form action="{% url 'blog:search' %}">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" placeholder="Search products..." title="search through blog"  required>
                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="submit"><i class="lnr lnr-magnifier"></i></button>
                                    </span>
                </div><!-- /input-group -->
                <div class="br"></div>
            </form>
            <div class="br"></div>
        </aside>
        <aside class="single_sidebar_widget author_widget">
            <img class="author_img rounded-circle" src="img/blog/author.png" alt="">
            <h4>Rajan khayamali</h4>
            <p>Senior blog writer</p>
            <div class="social_icon">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-github"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>
            <p>Boot camps have its supporters andit sdetractors. Some people do not understand why you
                should have to spend money on boot camp when you can get. Boot camps have itssuppor ters
                andits detractors.</p>
            <div class="br"></div>
        </aside>
        <aside class="single_sidebar_widget popular_post_widget">
            <h3 class="widget_title">Popular Posts</h3>
            {% for top_post in top_posts %}
                <div class="media post_item">
                    {% thumbnail top_post.image.image "100x60" crop="center" as im %}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
                    <div class="media-body">
                        <a href="{% url 'blog:single_blog' top_post.slug %}"><h3>{{ top_post.title }}</h3>
                        </a>
                        <p>{{ top_post.category }}</p>
                    </div>
                </div>
            {% endfor %}
            <div class="br"></div>
        </aside>
{#        <aside class="single_sidebar_widget ads_widget">#}
{#            <a href="#"><img class="img-fluid" src="img/blog/add.jpg" alt=""></a>#}
{#            <div class="br"></div>#}
{#        </aside>#}

    </div>
</div>

templates/search-result.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}

    <section class="home_banner_area blog_banner">
        <div class="banner_inner d-flex align-items-center">
            <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0"
                 data-background=""></div>
            <div class="container">
                <div class="blog_b_text text-center">
                    <h2>Dude You’re Getting <br/> a Telescope</h2>
                    <p>There is a moment in the life of any aspiring astronomer that it is time to buy that first</p>
                    <a class="white_bg_btn" href="#">View More</a>
                </div>
            </div>
        </div>
    </section>
<section class="blog_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="blog_left_sidebar">
                        {% for blog in search_results %}
                            <article class="row blog_item">
                                <div class="col-md-3">
                                    <div class="blog_info text-right">
                                        <div class="post_tag">
                                            <a class="active" href="#">{{ blog.category }}</a>

                                        </div>
                                        <ul class="blog_meta list">
                                            <li><a href="#">{{ blog.author }}<i class="lnr lnr-user"></i></a></li>
                                            <li><a href="#">{{ blog.Pub_date }}<i class="lnr lnr-calendar-full"></i></a>
                                            </li>
                                            <li><a href="#">1.2M Views<i class="lnr lnr-eye"></i></a></li>
                                            <li><a href="#">06 Comments<i class="lnr lnr-bubble"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <div class="blog_post">
                                        {% thumbnail blog.image.image "510x275" crop="center" as im %}
                                            <img src="{{ im.url }}">
                                        {% endthumbnail %}
                                        <div class="blog_details">
                                            <a href="{% url 'blog:single_blog' blog.slug %}">
                                                <h2>{{ blog.title |safe }}</h2></a>
                                            <p>{{ blog.content|truncatewords:50 | safe }}</p>
                                            <a href="{% url 'blog:single_blog' blog.slug %}"
                                               class="white_bg_btn">View More</a>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        {% endfor %}

                        <nav class="blog-pagination justify-content-center d-flex">
                            <ul class="pagination">
                                <li class="page-item">
                                    <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
                                    </a>
                                </li>
                                <li class="page-item"><a href="#" class="page-link">01</a></li>
                                <li class="page-item active"><a href="#" class="page-link">02</a></li>
                                <li class="page-item"><a href="#" class="page-link">03</a></li>
                                <li class="page-item"><a href="#" class="page-link">04</a></li>
                                <li class="page-item"><a href="#" class="page-link">09</a></li>
                                <li class="page-item">
                                    <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                {% include 'partials/side-search-content.html' %}
            </div>
        </div>
    </section>
{% endblock %}